# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    
schedules:
- cron: "0 18 * * Mon"
  displayName: Monday 11am PDT (6pm UTC) build
  branches:
    include:
    - main
  always: true   

pr: none

variables:
  - group: vssetup-apiscan

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
  pipelines:
  - pipeline: Vswhere-CI # identifier for the resource (used in pipeline resource variables)
    source: Setup-vswhere-CI # name of the pipeline that produces an artifact

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
      antimalwareScan:
        enabled: true
      armory:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      codeql:
        compiled:
          enabled: true
      credscan:
        enabled: true
      policheck:
        enabled: true
      psscriptanalyzer:
        enabled: true
      prefast:
        enabled: true
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)\.config\tsaoptions.json
        onboard: false

    stages:
      - stage: Compliance
        jobs:
          - job: Compliance
            steps:
              - download: Vswhere-CI
                artifact: drop

              - task: CopyFiles@2
                displayName: Copy files for API scan
                inputs:
                  SourceFolder: $(Pipeline.Workspace)\Vswhere-CI\drop
                  Contents: |
                    **\*.?(exe|dll|pdb|xml)
                  TargetFolder: $(Build.StagingDirectory)\apiscan-inputs

              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(Build.StagingDirectory)\apiscan-inputs
                  softwareName: 'Microsoft.VSWhere'
                  softwareVersionNum: '3'
                  toolVersion: Latest
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId)

              - task: PublishSecurityAnalysisLogs@3
                displayName: Publish 'SDLAnalysis-APIScan' artifact
                condition: succeededOrFailed()
                inputs:
                  ArtifactName: SDLAnalysis-APIScan
                  AllTools: false
                  APIScan: true

              - task: PostAnalysis@2
                displayName: Post Analysis
                inputs:
                  GdnBreakAllTools: false
                  GdnBreakGdnToolApiScan: true
                
              - task: TSAUpload@2
                displayName: Upload APIScan results to TSA
                inputs:
                  GdnPublishTsaOnboard: false
                  GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
                  GdnPublishTsaExportedResultsPublishable: true
                continueOnError: true
                condition: succeededOrFailed()
                enabled: true
