# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md

pr: none

queue:
  name: VSEngSS-MicroBuild2019-1ES
  timeoutInMinutes: 120
  demands: 
  - ChocolateyInstall
  - MSBuild
  - VisualStudio
  - VSTest

steps:
- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
  displayName: Install signing plugin
  inputs:
    signType: $(SignType)
    esrpSigning: true

- template: inc/build.yml
  parameters:
      BuildConfiguration: $(BuildConfiguration)
      BuildPlatform: $(BuildPlatform)
      Sign: true

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: Detect components
  inputs:
    sourceScanPath: $(Build.SourcesDirectory)

- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: Clean up
  condition: succeededOrFailed()
