queue:
  name: VSEng-MicroBuildVS2017
  timeoutInMinutes: 120
  demands: 
  - msbuild
  - visualstudio
  - vstest
  - Cmd

variables:
  solution: '**\*.sln'
  vsVersion: 15.0

steps:
- task: NuGetInstaller@0
  inputs:
    solution: $(solution)
    versionSpec: 4.1.0

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    esrpSigning: true

- task: VSBuild@1
  inputs:
    solution: $(solution)
    vsVersion: $(vsVersion)
    configuration: $(BuildConfiguration)
    platform: $(BuildPlatform)
    maximumCpuCount: true

- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\obj\**
    searchFolder: $(Build.SourcesDirectory)\bin\$(BuildConfiguration)
    vsTestVersion: $(vsVersion)
    runInParallel: true
    codeCoverageEnabled: true
    configuration: $(BuildConfiguration)
    platform: $(BuildPlatform)

- task: BatchScript@1
  inputs:
    filename: tools/choco.cmd
    arguments: pack pkg\vswhere\vswhere.nuspec --out "bin\$(BuildConfiguration)" --version "%GitBuildVersionSimple%" "Configuration=$(BuildConfiguration)" "CommitId=$(Build.SourceVersion)"
    workingFolder: $(Build.SourcesDirectory)

- task: VSBuild@1
  inputs:
    solution: pkg\vswhere\vswhere.signproj
    vsVersion: $(vsVersion)
    configuration: $(BuildConfiguration)
    platform: $(BuildPlatform)

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    Contents: |
     bin\$(BuildConfiguration)\**
     tools\**
    TargetFolder: $(Build.ArtifactStagingDirectory)\out

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\out
    ArtifactName: drop
    publishLocation: Container

- task: MicroBuildCleanup@1
  condition: succeededOrFailed()

# vim: set ai et st=2 sts=2 sw=2:
