# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    
schedules:
- cron: "0 18 * * Mon"
  displayName: Monday 11am PDT (6pm UTC) build
  branches:
    include:
    - main
  always: true   

pr: none

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
      antimalwareScan:
        enabled: true
      armory:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      codeql:
        compiled:
          enabled: true
      credscan:
        enabled: true
      policheck:
        enabled: true
      psscriptanalyzer:
        enabled: true
      prefast:
        enabled: true
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)\.config\tsaoptions.json

    stages:
      - stage: Compliance
        jobs:
          - job: Compliance
            templateContext:
            steps:
            - template: /pipelines/templates/build.yml@self
              parameters:
                  BuildConfiguration: $(BuildConfiguration)
                  BuildPlatform: $(BuildPlatform)
                  Sign: false
                  PublishArtifactTemplate: /pipelines/templates/1es-publish-task.yml@self
