configuration:
  - Debug
  - Release

image: Visual Studio 2017

environment:
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

test_script:
  - tools\test.cmd -v

artifacts:
  - path: bin\$(configuration)
    type: zip

# vim: set ai et st=2 sts=2 sw=2:
