configuration:
  - Debug
  - Release

image: Visual Studio 2017

environment:
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

install:
  - nuget restore

build:
  parallel: true

after_build:
  - tools\choco.cmd pack pkg\vswhere\vswhere.nuspec --out "bin\%CONFIGURATION%" --version "%GitBuildVersionSimple%" "Configuration=%CONFIGURATION%" "CommitId=%APPVEYOR_REPO_COMMIT%"

test_script:
  - tools\test.cmd -v

artifacts:
  - path: bin\$(configuration)\vswhere.exe
    name: vswhere

  - path: bin\$(configuration)
    type: zip

deploy:
  - provider: GitHub
    auth_token:
      secure: 5K94QY8dHKlbjvlBpQaXwAkmDf+LQE3g5WlU9snnNMjDjf0UT4xDoOBCLWcmwZOm
    artifact: vswhere
    prerelease: true
    on:
      # Signed releases will come from VSTS on master
      branch: develop
      configuration: Release

# vim: set ai et st=2 sts=2 sw=2:
