# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

# Would prefer to only use "image" in docker-compose.yml, but AppVeyor version of docker-compose fails
# stating that a "Dockerfile" in the current directory does not exist.
FROM heaths/vssetup:1.11.2290
